### ISSUE TITLE
Unknown exception when installing update

### ISSUE THREAD

**Issue by simon-suuk** [kolbasa/cordova-plugin-apkupdater#5]
Hi @kolbasa good work here!

Kindly look into version ```@1.1.5 ```. I get the following unknown exception when calling ```cordova.plugins.apkupdater.install()```.  However, it works fine with version ```@1.1.4 ```.

```
Installing update
VM262:1 Uncaught SyntaxError: missing ) after argument list
main-es2015.65833e749b32226b929f.js:1 ERROR Error: Uncaught (in promise): Unknown exception
    at v (polyfills-es2015.53442393c1b668685504.js:1)
    at polyfills-es2015.53442393c1b668685504.js:1
    at a (main-es2015.65833e749b32226b929f.js:1)
    at a.invoke (polyfills-es2015.53442393c1b668685504.js:1)
    at Object.onInvoke (main-es2015.65833e749b32226b929f.js:1)
    at a.invoke (polyfills-es2015.53442393c1b668685504.js:1)
    at s.run (polyfills-es2015.53442393c1b668685504.js:1)
    at polyfills-es2015.53442393c1b668685504.js:1
    at a.invokeTask (polyfills-es2015.53442393c1b668685504.js:1)
    at Object.onInvokeTask (main-es2015.65833e749b32226b929f.js:1)
```

**Comment by kolbasa** [comment]
Hello and thanks for the question.
However, I cannot reproduce it. It sounds like a typo in your code.

I did the following:
```js
await cordova.plugins.apkupdater.check('https://raw.githubusercontent.com/kolbasa/cordova-plugin-apkupdater-demo/master/update/manifest.json');
await cordova.plugins.apkupdater.download();
await cordova.plugins.apkupdater.install();
```
This also works with version @ 1.1.5.
If you post your code, maybe I can see more.

**Comment by simon-suuk** [comment]
Thanks for the reply! I was able to fix the issue.

I was using nested callbacks at first. I changed them to promises.

For example I changed this 
```
cordova.plugins.apkupdater.check('https://your-domain.com/update/manifest.json',
      manifest => {
        doSomethingWith(manifest).then(response => {
          doAnotherThing(response);
        });
      },
      error => {
        console.log(error);
      }
);
```


To this
```
const manifest = await cordova.plugins.apkupdater.check('https://your-domain.com/update/manifest.json');
const response = await doSomethingWith(manifest);
doAnotherThing(response);
```
